### ISSUE TITLE
¿Posible bug? [Op no muere]

### ISSUE THREAD

**Issue by Necz1504** [SebazCRC/PermaDeathCore#10]
**Versiones**
Plugin: [1.0-PRE-RELEASE]
Minecraft: [1.16]
Tipo y versión del servidor: Spigot

**Describe el bug**
No se si cuenta como bug pero igualmente lo reporto. A la hora de que un admin (op) muera no sale el mensaje de muerte pero no es baneado mientras que alguien que no es op al morir es baneado.
**Como reproducirlo**
Indica los pasos para reproducir el bug:
1- Ser Op
2- Morir
3- [...]
4- [...]

**Que debería pasar**
El jugador que sea Op debería de ser baneado

**Capturas de pantalla**
Si necesitas, puedes colocar capturas de pantalla aquí.

**Información adicional**
Como información adicional he de decir que esto no ocurrirá en la antigua versión del plugin

**Comment by SebazCRC** [comment]
Los jugadores con el permiso
permadeathcore.banoverride
No son capaces de morir, el mismo chat dice "El jugador... No puede...", no es un bug, está diseñado así a propósito.


Guerrero no cierres esta
