### ISSUE TITLE
PermadeathCore Reloaded No carga en Aternos. Posible Bug

### ISSUE THREAD

**Issue by gcoffc** [SebazCRC/PermaDeathCore#11]
**Versiones**
Plugin: [1.0-PRE-RELEASE]
Minecraft: [1.15]
Tipo y versión del servidor: [Spigot]

**Describe el bug**
El plugin no funciona en aternos

**Como reproducirlo**
Indica los pasos para reproducir el bug:
1- Instalar la ultima version del plugin en aternos
2- Abrir el servidor
3- Intentar ver los cambios de dificultad o poner el comando /pdc

**Que debería pasar**
El plugin debería funcionar con normalidad, y los cambios de dificultad tambien.

**Capturas de pantalla**
https://i.imgur.com/YlSxUN3.png

**Información adicional**

En la pagina de aternos sale "La extension 'PermaDeathCoreReloaded' necesita la extensión 'Unknown'.
Posibles soluciones: -Instalar el plugin 'Unknown'
                                 -Eliminar el archivo 'plugins/PermaDeathCoreReloaded.jar'. "

El servidor fue iniciado hace un mes aproximadamente con la versión original del plugin (PermaDeathCore), puede que ese sea uno de los problemas que este teniendo.

**Comment by GuerreroCraft61** [comment]
Tienes instalado World Edit?

**Comment by gcoffc** [comment]
No,  gracias por informarme, se me habia olvidado instalarlo.
