### ISSUE TITLE
[Plugin Bug] Pico de netherite encantado te quita vida

### ISSUE THREAD

**Issue by Samztx** [SebazCRC/PermaDeathCore#12]
**Versiones**
Plugin: [1.0-PRE-RELEASE]
Minecraft: [1.14, 1.15, 1.16]
Tipo y versión del servidor: [Bukkit, Spigot, Paper] vXXXXX

**Describe el bug**
Cuando encantas un pico de netherite te empieza a quitar daño como un pico de diamante
**Como reproducirlo**
Indica los pasos para reproducir el bug:
1- Obtener el pico de netherite
2- Encantarlo
3- Picar un bloque
4- [...]

**Que debería pasar**
No te debe de hacer daño

**Capturas de pantalla**
https://cdn.discordapp.com/attachments/731945312733888622/732945925923668028/unknown.png

**Información adicional**
Aquí puedes dar información adicional como por ejemplo el contexto de lo sucedido o por ejemplo el Log de la consola.

**Comment by SebazCRC** [comment]
Efectivamente, recordemos que el día 50 está en desarrollo, por lo que es experimental, este problema lo confirmamos como bug.

**Comment by Samztx** [comment]
Pues ya me esperaba que este bug era conocido, pero bueno.

Suerte con el dia 50! Ojala lo termines pronto
