### ISSUE TITLE
[Plugin Bug] Armor de Netherite

### ISSUE THREAD

**Issue by Sieniemand** [SebazCRC/PermaDeathCore#16]
Versiones
Plugin: [1.0-PRE-RELEASE-2]
Minecraft: [1.15]
Tipo y versión del servidor: [Spigot]

Describe el bug
Se recibe daño al tener puesta la armadura de netherite, pero no se pierde vida, solo se ve como si recibieras golpes y puede ocasionalmente aparecerte una pantalla de muerte. 

Como reproducirlo
Indica los pasos para reproducir el bug:
1- [Equiparse netherite]
2- [Dejar pasar unos minutos]

Que debería pasar
No debería recibir golpes ni pantallas de muerte.

**Comment by SebazCRC** [comment]
Necesito video, de lo contrario esto será ignorado

**Comment by Sieniemand** [comment]
Ok, veré de hacer uno
