### ISSUE TITLE
Bug con los aldeanos hostiles

### ISSUE THREAD

**Issue by juandiaz04** [SebazCRC/PermaDeathCore#17]
**Versiones**
Plugin: [1.0-PRE-RELEASE]
Minecraft: [1.14, 1.15, 1.16]
Tipo y versión del servidor: [Bukkit, Spigot, Paper] vXXXXX

**Describe el bug**
Al acercarte a aldeanos que están durmiendo a partir del día 20, te persiguen para atacarte pero se mantienen en la posición de 'tumbados'

**Como reproducirlo**
Indica los pasos para reproducir el bug:
1- Esperar a que los aldeanos duerman de noche
2- Acercarte lo suficiente a ellos

**Que debería pasar**
Que los aldeanos no reaccionen o que se despierten y te ataquen

**Capturas de pantalla**
Si necesitas, puedes colocar capturas de pantalla aquí.

**Información adicional**
Aquí puedes dar información adicional como por ejemplo el contexto de lo sucedido o por ejemplo el Log de la consola.

**Comment by SebazCRC** [comment]
Buenas, creo que sí, efectivamente es un bug, pero nada que afecte la jugabilidad, esto es más bien de Minecraft, yo no puedo hacer que unos aldeanos se levanten de la cama, por lo tanto, esto no lo contaré, tampoco es algo que afecte el gameplay

**Comment by juandiaz04** [comment]
Si que afecta, me dejaron a medio antes ._.

**Comment by juancruz170301** [comment]
El juego no esta programado para que los aldeanos sean agresivos, es normal, y tampoco creo que sea un bug, ellos te detectan y se levantan, como lo hacen con los zombies
