### ISSUE TITLE
[Plugin Bug] Armadura de netherite no da corazones extras

### ISSUE THREAD

**Issue by EmanuellHEA** [SebazCRC/PermaDeathCore#2]
**Versiones**
Plugin: [1.0-PRE-RELEASE]
Minecraft: 1.15.2
Tipo y versión del servidor:Paper

**Describe el bug**
No sé obtienen los corazones extra con la armadura de netherite
![SAVE_20200713_140642](https://user-images.githubusercontent.com/68249309/87346363-2ee68380-c517-11ea-90ec-ee5b476fc968.jpg)

**Que debería pasar**
La armadura deberia dar 4 corazones extra

**Comment by SebazCRC** [comment]
No renombres la armadura, hace que deje de funcionar correctamente
