### ISSUE TITLE
Anuncios de  PermadeathCore Bug

### ISSUE THREAD

**Issue by CristoPG800** [SebazCRC/PermaDeathCore#20]
**Versiones**
Plugin: [PRE-RELEASE-3]
Minecraft: [1.14, 1.15, 1.16]
Tipo y versión del servidor: [Bukkit, Spigot, Paper] vXXXXX

**Describe el bug**
Los anuncios de permadeathcore salen cada un segundo y no cada 30 minutos como ofrece el Creador de este plugin

**Que debería pasar**
Deberian salir anuncios cada 30 minutos 

**Capturas de pantalla**
![Uploading 15966833061971944940959679522227.jpg…]()

**Información adicional**
Con estos anuncios cada 1 segundo no se puede disfrutar el plugin por que los comandos se pierden en el chat

**Comment by NotEmpanamorse** [comment]
La captura de pantalla que has dado no se carga, intenta enviarla de nuevo o usa una web como [https://imgur.com/](https://imgur.com/)

**Comment by SebazCRC** [comment]
Son cada 25 minutos lo he probado, esto no es un bug, lo que si spamea es si no tienes world edit, ejemplo, si no tienes el plugin de World Edit, se te spameará cada segundo que lo instales.

Marcado como descartado.
