### ISSUE TITLE
[Plugin Bug] Multiverse

### ISSUE THREAD

**Issue by sioa** [SebazCRC/PermaDeathCore#21]
**Versiones**
Plugin: [1.0-PRE-RELEASE]
Minecraft: [1.14, 1.15, 1.16]
Tipo y versión del servidor: [Bukkit, Spigot, Paper] vXXXXX

**Describe el bug**
En la configuración se da la opción de seleccionar el mundo donde se aplicará (MainWorld y EndWorld) sin embargo si se cuentan con más mundos los efectos / mensajes / y recopilación de datos se realiza en todos los mundos existentes.  

Paper 1.16

**Como reproducirlo**
Indica los pasos para reproducir el bug:
1- [Se crean mundos con Multiverse Core]
2- [Se selecciona el mundo por defecto en la configuración del plugin]
3- [Morir en un mundo distinto al indicado en el config]
4- [...]

**Que debería pasar**
Los efectos y mensajes solo deberían aparecer en el mundo señalado

**Capturas de pantalla**
1.- Imagen desde el world (se ve el texto del plugin) siendo que por configuración está activo en el world2
https://imgur.com/dw9tUXz

2.- Morí en el mundo uno y comenzó el evento (visible desde ambos mundos) 
https://imgur.com/GjGqS2e 
https://imgur.com/ljBtNHs
https://imgur.com/MHVhsAS

3.- Imagen de la configuración donde se señala el mundo 
https://imgur.com/bHn9tmO

**Información adicional**
Desconozco si esto es un bug o el plugin no contempla el control de mundos 

Muchas gracias por la ayuda!

**Comment by SebazCRC** [comment]
Buenas, muy completo la verdad gracias, pero si te fijas al poner un mundo sólo comenzará tormenta en él, o sea, en el resto no, y en cualquier mundo que estés siempre se mostrará el action bar y mensajes cuando alguien muere, a continuación explicaré cómo funcionan estos ajustes.

El mundo por defecto es donde el plugin recolectará información de tormenta y así mismo la dará, y esto lo mandará a cada jugador en línea, el típico "Quedan xx de tormenta"

Ahora bien el mundo del end, es el que le dice al plugin donde aparecerán ender creepers ghasts y esos mobs y que allí funcionen. 

En conclusión el plugin no está hecho para que juegues en múltiples mundos, si deseas hacer eso, monta una network con bungeecord y colocas distintos servidores y un lobby. 
Detalle extra: Te recomiendo eliminar Multiverse Core, puede causar problemas con TheBeginning

**Comment by sioa** [comment]
Gracias por la recomendación, instale el Bungeecord y todo perfecto.
