### ISSUE TITLE
[Plugin Bug]

### ISSUE THREAD

**Issue by MichaelSenabre** [SebazCRC/PermaDeathCore#24]
**Versiones**
Plugin: [1.0.0]
Minecraft: [1.15]
Tipo y versión del servidor: [Paper] #385

**Describe el bug**
En el mundo de el end y en el mundo de thebeginning los ghasts son "invulnerables" quiero decir que cuando les disparas la flecha rebota en ellos y se va al suelo, pero si el gahst lo spawneas tu mismo con un huevo si que se le puede dar

**Como reproducirlo**
Indica los pasos para reproducir el bug:
1- Ir al end o a the beginning
2- Buscar un ghast y dispararle con un arco ya que con la espada si que se le hace daño
3- Contemplar lo que ocurre

**Que debería pasar**
Que al ghast no le rebotase la bala y si que se le pudiese hacer daño con el arco

**Capturas de pantalla**
Si necesitas, puedes colocar capturas de pantalla aquí.

**Información adicional**
Aquí puedes dar información adicional como por ejemplo el contexto de lo sucedido o por ejemplo el Log de la consola.

**Comment by SebazCRC** [comment]
Bug fue solucionado en la 1.0.0, descartado
