### ISSUE TITLE
Bug de multiplicacion al crear Hyper Golden Apple +

### ISSUE THREAD

**Issue by MrCamil0** [SebazCRC/PermaDeathCore#6]
Plugin: 1.0-PRE-RELEASE
Minecraft: 1.15.2
Tipo y versión del servidor: Paper

Cuando crafteas una Hyper Golden Apple + con un stack de manzanas de oro en el centro estas se duplican y cuando sacas las manzanas de la mesa de crafteo tienes 126 (1 stack y 62).

**Como reproducirlo**
Indica los pasos para reproducir el bug:
1- Craftear una Hyper Golden Apple +
2- En el medio poner 1 stack de manzanas de oro
3- Craftear la Hyper Golden Apple +
4- Luego recoger las manzanas que quedaron en el centro y el bug se vera

**Que debería pasar**
Tendrian que quedar las 63 manzanas de oro en vez de 126.

**Capturas de pantalla**
https://user-images.githubusercontent.com/68255073/87363064-f6a26d80-c535-11ea-8fe6-ab204ca2c3e3.png

**Información adicional**
No creo que haya una información adicional que dar más que la consola no decia nada.

**Comment by SebazCRC** [comment]
Lamentablemente, este bug es de spigot, nada que pueda hacer
