### ISSUE TITLE
Armadura de Netherrite Infernal

### ISSUE THREAD

**Issue by Necz1504** [SebazCRC/PermaDeathCore#7]
**Versiones**
Plugin: [1.0-PRE-RELEASE]
Minecraft: [1.16]
Tipo y versión del servidor: [Spigot] 

**Describe el bug**
Lo que pasa con el bug es que a la hora de craftear la armadura de Netherrite Infernal no funciona ya que no sale el crafteo. ( Con armadura de Netherrite)

**Como reproducirlo**
Indica los pasos para reproducir el bug:
1- colocar armadura de Netherrite ( la normal es decir la que no sueltan los mobs)
2- colocar los Infernal Netherrite Block rodeando la armadura en forma de cruz
3- 
4- [...]

**Que debería pasar**
Deberían de salir las armaduras infernales

**Capturas de pantalla**
![15947362490453392921802508829204](https://user-images.githubusercontent.com/68284727/87436909-f1a0f500-c5ed-11ea-9e80-22873bad8354.jpg)

**Información adicional**

**Comment by SebazCRC** [comment]
Las recetas se registran al empezar el servidor en el día 50, no con /pdc cambiardia 50

Además recordemos que no está del todo diseñado para 1.16
