### ISSUE TITLE
Bug Ender Quantum Creeper 

### ISSUE THREAD

**Issue by AshKetxups** [SebazCRC/PermaDeathCore#8]
**Versiones**
Plugin: [1.0-PRE-RELEASE]
Minecraft: [1.14, 1.15, 1.16]
Tipo y versión del servidor: [Bukkit, Spigot, Paper] vXXXXX

Lo que pasa es que el Ender Quantum Creeper no explota como debería y lo que debería pasar es que destruya todos los bloques.

**Comment by AloncraftMC** [comment]
Los Ender Quantum Creepers son del día 60 y no están hechos aún, te estás refiriendo a los Quantum Creepers, que lo que hacen es dejar la nube de efectos y no reventar bloques. Deberías saber los cambios y como funcionan antes de comentar
