### ISSUE TITLE
Bug de spawn de Ender Ghasts

### ISSUE THREAD

**Issue by SergiDRV** [SebazCRC/PermaDeathCore#9]
**Versiones**
Plugin: 1.0-PRE-RELEASE
Minecraft: 1.15.2
Tipo y versión del servidor: Paper-378

**Describe el bug**
No se spawnean Ender Ghasts durante la batalla contra el Permadeath Demon, pero cuando lo matas empiezan a spawnear.

**Como reproducirlo**
1- Entrar al End cuando el Permadeath Demon sigue vivo.

**Que debería pasar**
Se deberían spawnear Ender Ghasts durante la batalla contra el Permadeath Demon.

**Capturas de pantalla**
![2020-07-15_13 48 37](https://user-images.githubusercontent.com/68329204/87542568-6f730800-c6a3-11ea-84ff-ac2f3878a56c.png)
![2020-07-15_13 48 49](https://user-images.githubusercontent.com/68329204/87542601-7f8ae780-c6a3-11ea-9a2c-292f3dfbbe26.png)
![2020-07-15_13 49 01](https://user-images.githubusercontent.com/68329204/87542624-8c0f4000-c6a3-11ea-9efb-e7657a82e372.png)
![2020-07-15_13 52 13](https://user-images.githubusercontent.com/68329204/87542630-8e719a00-c6a3-11ea-9e51-95659ed5503a.png)

**Información adicional**
En la última imagen se puede ver que al abrirse el portal después de matar al Permadeath Demon, empiezan a aparecer Ender Ghasts.

**Comment by SebazCRC** [comment]
SergiDRV

Esto no es un bug, los ender ghasts NO pueden spawnear durante la batalla, recuerda que spawnean al romper un cristal. 
Mejor infórmate antes de criticar, ya que así es en perma :/

**Comment by SergiDRV** [comment]
Vale, perdón por estar mal informado :(
